apiVersion: v1
kind: Service
metadata:
  name: myappsvc
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gyaleholi-quay-hands-on.apps.gmseng02.ocp02.eng/repository/admin123/demo:02298840-b134-4294-aa2f-1c038585ee2a
        ports:
        - containerPort: 80

