apiVersion: v1
kind: Service
metadata:
  name: myappsvc
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: v1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      containers:
      - name: myapp
        image: argo:a94911a4-f8a3-4b79-8167-f93561784e74
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

