apiVersion: v1
kind: Service
metadata:
  name: myappsvc
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gyaleholi-quay-hands-on.apps.gmseng02.ocp02.eng/admin123/demo:69824f9a-9a75-458d-ba59-b67dbd2735d1
        ports:
        - containerPort: 8080

